{"uid":"2315d81a62754446","name":"test_delete_user_authorized_as_another_user","fullName":"tests.test_user_delete.TestUserDelete#test_delete_user_authorized_as_another_user","historyId":"f921dd3d5d139c34912ef23ea50982dc","time":{"start":1712812058411,"stop":1712812062851,"duration":4440},"description":"This test verifies that one user cannot delete another user","descriptionHtml":"<p>This test verifies that one user cannot delete another user</p>\n","status":"passed","statusMessage":"XPASS This test is expected to fail due to a known defect","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"description":"This test verifies that one user cannot delete another user","status":"passed","statusMessage":"XPASS This test is expected to fail due to a known defect","steps":[{"name":"POST request to URL '/user/'","time":{"start":1712812058411,"stop":1712812059319,"duration":908},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"POST request to URL '/user/'","time":{"start":1712812059319,"stop":1712812060223,"duration":904},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"POST request to URL '/user/login'","time":{"start":1712812060224,"stop":1712812060622,"duration":398},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"DELETE request to URL '/user/95892'","time":{"start":1712812060622,"stop":1712812061856,"duration":1234},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"GET request to URL '/user/95892'","time":{"start":1712812061856,"stop":1712812062847,"duration":991},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":5,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"epic","value":"User Deletion Tests"},{"name":"tag","value":"@pytest.mark.xfail(reason='This test is expected to fail due to a known defect')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_user_delete"},{"name":"subSuite","value":"TestUserDelete"},{"name":"host","value":"fv-az774-42"},{"name":"thread","value":"2285-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_user_delete"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":0,"skipped":153,"passed":33,"unknown":0,"total":186},"items":[{"uid":"99e737ea5c86776a","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/187//#testresult/99e737ea5c86776a","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1712726905813,"stop":1712727180351,"duration":274538}},{"uid":"172b866ff21f932c","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/186//#testresult/172b866ff21f932c","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1712639238313,"stop":1712639243400,"duration":5087}},{"uid":"3990dadc825ba14d","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/185//#testresult/3990dadc825ba14d","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1712552876722,"stop":1712552881723,"duration":5001}},{"uid":"95855c0462bb6f84","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/184//#testresult/95855c0462bb6f84","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1712466474249,"stop":1712466478841,"duration":4592}},{"uid":"9289f2b4f6e56019","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/183//#testresult/9289f2b4f6e56019","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1712380055968,"stop":1712380060861,"duration":4893}},{"uid":"aa4de00578e5f542","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/182//#testresult/aa4de00578e5f542","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1712293637493,"stop":1712293642117,"duration":4624}},{"uid":"dd7e214d20ad9ea2","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/181//#testresult/dd7e214d20ad9ea2","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1712207275311,"stop":1712207279813,"duration":4502}},{"uid":"5feb1d4195acb394","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/180//#testresult/5feb1d4195acb394","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1712120846875,"stop":1712120851874,"duration":4999}},{"uid":"d12320fa5811cc6","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/179//#testresult/d12320fa5811cc6","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1712034425821,"stop":1712034430461,"duration":4640}},{"uid":"5e7802684015185d","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/178//#testresult/5e7802684015185d","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1711948070262,"stop":1711948075529,"duration":5267}},{"uid":"134761138735999e","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/177//#testresult/134761138735999e","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1711861647352,"stop":1711861652307,"duration":4955}},{"uid":"587721f4e3e34e5a","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/176//#testresult/587721f4e3e34e5a","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1711775250648,"stop":1711775255285,"duration":4637}},{"uid":"5d9d61c9ff0474ff","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/175//#testresult/5d9d61c9ff0474ff","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1711688875157,"stop":1711688880142,"duration":4985}},{"uid":"7f725811ba87808a","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/174//#testresult/7f725811ba87808a","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1711602485121,"stop":1711602490121,"duration":5000}},{"uid":"333a17204ef54b8c","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/173//#testresult/333a17204ef54b8c","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nAssertionError: Unexpected status code 200\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code","time":{"start":1711516089016,"stop":1711516092531,"duration":3515}},{"uid":"71bc46d2853ab961","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/172//#testresult/71bc46d2853ab961","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1711429612054,"stop":1711429616667,"duration":4613}},{"uid":"f2b29b874cd1dc75","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/171//#testresult/f2b29b874cd1dc75","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1711343269887,"stop":1711343275509,"duration":5622}},{"uid":"cec05788442c7dc6","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/170//#testresult/cec05788442c7dc6","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1711256864053,"stop":1711256869156,"duration":5103}},{"uid":"63fe67a618a15a40","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/169//#testresult/63fe67a618a15a40","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nAssertionError: Unexpected status code 200\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code","time":{"start":1711170442024,"stop":1711170445572,"duration":3548}},{"uid":"23fab20a37d3122a","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/168//#testresult/23fab20a37d3122a","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1711084083653,"stop":1711084088898,"duration":5245}}]},"tags":["@pytest.mark.xfail(reason='This test is expected to fail due to a known defect')"]},"source":"2315d81a62754446.json","parameterValues":[]}