{"uid":"cb97bc0df4acf7a2","name":"test_delete_user_authorized_as_another_user","fullName":"tests.test_user_delete.TestUserDelete#test_delete_user_authorized_as_another_user","historyId":"f921dd3d5d139c34912ef23ea50982dc","time":{"start":1730437798330,"stop":1730437802820,"duration":4490},"description":"This test verifies that one user cannot delete another user","descriptionHtml":"<p>This test verifies that one user cannot delete another user</p>\n","status":"passed","statusMessage":"XPASS This test is expected to fail due to a known defect","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"description":"This test verifies that one user cannot delete another user","status":"passed","statusMessage":"XPASS This test is expected to fail due to a known defect","steps":[{"name":"POST request to URL '/user/'","time":{"start":1730437798330,"stop":1730437799298,"duration":968},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"POST request to URL '/user/'","time":{"start":1730437799298,"stop":1730437800244,"duration":946},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"POST request to URL '/user/login'","time":{"start":1730437800244,"stop":1730437800679,"duration":435},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"DELETE request to URL '/user/108587'","time":{"start":1730437800679,"stop":1730437801755,"duration":1076},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"GET request to URL '/user/108587'","time":{"start":1730437801755,"stop":1730437802819,"duration":1064},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":5,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"epic","value":"User Deletion Tests"},{"name":"tag","value":"@pytest.mark.xfail(reason='This test is expected to fail due to a known defect')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_user_delete"},{"name":"subSuite","value":"TestUserDelete"},{"name":"host","value":"fv-az654-502"},{"name":"thread","value":"2296-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_user_delete"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":0,"skipped":160,"passed":230,"unknown":0,"total":390},"items":[{"uid":"86ef4e17d1902e38","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/391//#testresult/86ef4e17d1902e38","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1730351372964,"stop":1730351377483,"duration":4519}},{"uid":"67f27b9a7bdbc61","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/390//#testresult/67f27b9a7bdbc61","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='playground.learnqa.ru', port=443): Max retries exceeded with url: /api/user/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fbe06e122d0>, 'Connection to playground.learnqa.ru timed out. (connect timeout=None)'))","time":{"start":1730272014208,"stop":1730272554809,"duration":540601}},{"uid":"cac02eaafeb4eee7","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/389//#testresult/cac02eaafeb4eee7","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='playground.learnqa.ru', port=443): Max retries exceeded with url: /api/user/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb51ae3a510>, 'Connection to playground.learnqa.ru timed out. (connect timeout=None)'))","time":{"start":1730185594094,"stop":1730186134695,"duration":540601}},{"uid":"c85ced0564f13db2","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/388//#testresult/c85ced0564f13db2","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1730092224182,"stop":1730092228953,"duration":4771}},{"uid":"cb1be9e8b25a5a99","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/387//#testresult/cb1be9e8b25a5a99","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1730005766381,"stop":1730005771283,"duration":4902}},{"uid":"54f6e91135c9c4f9","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/386//#testresult/54f6e91135c9c4f9","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1729919334309,"stop":1729919339366,"duration":5057}},{"uid":"fc3a42f6a404b893","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/385//#testresult/fc3a42f6a404b893","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1729833029155,"stop":1729833034292,"duration":5137}},{"uid":"ca8526cebc81b926","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/384//#testresult/ca8526cebc81b926","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1729746585350,"stop":1729746590829,"duration":5479}},{"uid":"59931054cf5c6014","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/383//#testresult/59931054cf5c6014","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1729660208418,"stop":1729660213650,"duration":5232}},{"uid":"64ccabb1cf333794","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/382//#testresult/64ccabb1cf333794","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1729573767219,"stop":1729573771959,"duration":4740}},{"uid":"3e24c1f7eb1c6736","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/381//#testresult/3e24c1f7eb1c6736","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1729487407629,"stop":1729487411917,"duration":4288}},{"uid":"9f9e2d095fff8957","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/380//#testresult/9f9e2d095fff8957","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1729400938585,"stop":1729400943554,"duration":4969}},{"uid":"c5261cf3bbaad739","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/379//#testresult/c5261cf3bbaad739","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1729314516056,"stop":1729314520841,"duration":4785}},{"uid":"9837292f747ebcce","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/378//#testresult/9837292f747ebcce","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1729228188753,"stop":1729228194002,"duration":5249}},{"uid":"f2bf4f6143b8231d","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/377//#testresult/f2bf4f6143b8231d","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1729141765548,"stop":1729141770139,"duration":4591}},{"uid":"5d79df7cce7d276e","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/376//#testresult/5d79df7cce7d276e","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1729055374513,"stop":1729055378935,"duration":4422}},{"uid":"7d8cab51085922f6","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/375//#testresult/7d8cab51085922f6","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1728969011949,"stop":1728969016630,"duration":4681}},{"uid":"abf3b2bdc492cdf2","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/374//#testresult/abf3b2bdc492cdf2","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1728882586921,"stop":1728882592938,"duration":6017}},{"uid":"98b284b62f839b29","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/373//#testresult/98b284b62f839b29","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1728796170826,"stop":1728796175299,"duration":4473}},{"uid":"77ee885f7def5821","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/372//#testresult/77ee885f7def5821","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1728709731090,"stop":1728709735754,"duration":4664}}]},"tags":["@pytest.mark.xfail(reason='This test is expected to fail due to a known defect')"]},"source":"cb97bc0df4acf7a2.json","parameterValues":[]}