{"name": "test_summary", "status": "passed", "statusDetails": {"message": "XPASS Test passes individually but may fail in a suite run"}, "description": "Final test to check if there were any identification errors for User Agents", "start": 1697124019598, "stop": 1697124019599, "uuid": "a7209d8b-157e-4cec-8e82-74eb8baa96b5", "historyId": "60e3e602e149baf1e578e11e95f1fb22", "testCaseId": "60e3e602e149baf1e578e11e95f1fb22", "fullName": "tests.test_user_auth.TestUserAuth#test_summary", "labels": [{"name": "epic", "value": "Authorization cases"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='Test passes individually but may fail in a suite run')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_auth"}, {"name": "subSuite", "value": "TestUserAuth"}, {"name": "host", "value": "LAPTOP-SFQ2DO00"}, {"name": "thread", "value": "16560-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_auth"}]}