{"uid":"7c24c3093de8f2fe","name":"test_delete_user_authorized_as_another_user","fullName":"tests.test_user_delete.TestUserDelete#test_delete_user_authorized_as_another_user","historyId":"f921dd3d5d139c34912ef23ea50982dc","time":{"start":1730956164537,"stop":1730956169209,"duration":4672},"description":"This test verifies that one user cannot delete another user","descriptionHtml":"<p>This test verifies that one user cannot delete another user</p>\n","status":"passed","statusMessage":"XPASS This test is expected to fail due to a known defect","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"description":"This test verifies that one user cannot delete another user","status":"passed","statusMessage":"XPASS This test is expected to fail due to a known defect","steps":[{"name":"POST request to URL '/user/'","time":{"start":1730956164537,"stop":1730956165648,"duration":1111},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"POST request to URL '/user/'","time":{"start":1730956165648,"stop":1730956166542,"duration":894},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"POST request to URL '/user/login'","time":{"start":1730956166542,"stop":1730956167187,"duration":645},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"DELETE request to URL '/user/108712'","time":{"start":1730956167187,"stop":1730956168197,"duration":1010},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"GET request to URL '/user/108712'","time":{"start":1730956168197,"stop":1730956169209,"duration":1012},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":5,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"epic","value":"User Deletion Tests"},{"name":"tag","value":"@pytest.mark.xfail(reason='This test is expected to fail due to a known defect')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_user_delete"},{"name":"subSuite","value":"TestUserDelete"},{"name":"host","value":"fv-az1498-585"},{"name":"thread","value":"2296-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_user_delete"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":0,"skipped":161,"passed":235,"unknown":0,"total":396},"items":[{"uid":"6eb270c7320f95f1","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/397//#testresult/6eb270c7320f95f1","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1730869774173,"stop":1730869780021,"duration":5848}},{"uid":"e78e369109c69fb7","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/396//#testresult/e78e369109c69fb7","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1730783357891,"stop":1730783362282,"duration":4391}},{"uid":"3116bda30391a85","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/395//#testresult/3116bda30391a85","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nAssertionError: Unexpected status code 200\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code","time":{"start":1730697026092,"stop":1730697029907,"duration":3815}},{"uid":"6c374a588c33ad2a","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/394//#testresult/6c374a588c33ad2a","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1730610530915,"stop":1730610535395,"duration":4480}},{"uid":"294ea089f3afc338","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/393//#testresult/294ea089f3afc338","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1730524159811,"stop":1730524164785,"duration":4974}},{"uid":"cb97bc0df4acf7a2","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/392//#testresult/cb97bc0df4acf7a2","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1730437798330,"stop":1730437802820,"duration":4490}},{"uid":"86ef4e17d1902e38","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/391//#testresult/86ef4e17d1902e38","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1730351372964,"stop":1730351377483,"duration":4519}},{"uid":"67f27b9a7bdbc61","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/390//#testresult/67f27b9a7bdbc61","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='playground.learnqa.ru', port=443): Max retries exceeded with url: /api/user/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fbe06e122d0>, 'Connection to playground.learnqa.ru timed out. (connect timeout=None)'))","time":{"start":1730272014208,"stop":1730272554809,"duration":540601}},{"uid":"cac02eaafeb4eee7","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/389//#testresult/cac02eaafeb4eee7","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='playground.learnqa.ru', port=443): Max retries exceeded with url: /api/user/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb51ae3a510>, 'Connection to playground.learnqa.ru timed out. (connect timeout=None)'))","time":{"start":1730185594094,"stop":1730186134695,"duration":540601}},{"uid":"c85ced0564f13db2","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/388//#testresult/c85ced0564f13db2","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1730092224182,"stop":1730092228953,"duration":4771}},{"uid":"cb1be9e8b25a5a99","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/387//#testresult/cb1be9e8b25a5a99","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1730005766381,"stop":1730005771283,"duration":4902}},{"uid":"54f6e91135c9c4f9","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/386//#testresult/54f6e91135c9c4f9","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1729919334309,"stop":1729919339366,"duration":5057}},{"uid":"fc3a42f6a404b893","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/385//#testresult/fc3a42f6a404b893","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1729833029155,"stop":1729833034292,"duration":5137}},{"uid":"ca8526cebc81b926","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/384//#testresult/ca8526cebc81b926","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1729746585350,"stop":1729746590829,"duration":5479}},{"uid":"59931054cf5c6014","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/383//#testresult/59931054cf5c6014","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1729660208418,"stop":1729660213650,"duration":5232}},{"uid":"64ccabb1cf333794","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/382//#testresult/64ccabb1cf333794","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1729573767219,"stop":1729573771959,"duration":4740}},{"uid":"3e24c1f7eb1c6736","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/381//#testresult/3e24c1f7eb1c6736","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1729487407629,"stop":1729487411917,"duration":4288}},{"uid":"9f9e2d095fff8957","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/380//#testresult/9f9e2d095fff8957","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1729400938585,"stop":1729400943554,"duration":4969}},{"uid":"c5261cf3bbaad739","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/379//#testresult/c5261cf3bbaad739","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1729314516056,"stop":1729314520841,"duration":4785}},{"uid":"9837292f747ebcce","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/378//#testresult/9837292f747ebcce","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1729228188753,"stop":1729228194002,"duration":5249}}]},"tags":["@pytest.mark.xfail(reason='This test is expected to fail due to a known defect')"]},"source":"7c24c3093de8f2fe.json","parameterValues":[]}